### ISSUE TITLE
Run Error

### ISSUE THREAD

**Issue by wellmslouis** [baoguangsheng/fast-detect-gpt#2]
Hello! Thanks for your code!
When I run "python scripts/local_infer.py", the error appears.
```
../cache\local.EleutherAI_gpt-neo-2.7B does not appear to have a file named config.json. Checkout 'https://huggingface.co/../cache\local.EleutherAI_gpt-neo-2.7B/None' for available files.
urllib3.exceptions.SSLError: EOF occurred in violation of protocol (_ssl.c:997)

Traceback (most recent call last):
  File "D:\WELL\test_2\venv\lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
  File "D:\WELL\test_2\venv\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "D:\WELL\test_2\venv\lib\site-packages\huggingface_hub\utils\_http.py", line 63, in send
    return super().send(request, *args, **kwargs)
  File "D:\WELL\test_2\venv\lib\site-packages\requests\adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: (MaxRetryError("HTTPSConnectionPool(host='cdn-lfs.huggingface.co', port=443): Max retries exceeded with url: /EleutherAI/gpt-neo-2.7B/bd06eed99c791348df5bec014bd399960ef364b9951e1be8180940a3669a9067?response-content-disposition=attachment%3B+filename*%3DUTF-8%27%27pytorch_model.bin%3B+filename%3D%22pytorch_model.bin%22%3B&response-content-type=application%2Foctet-stream&Expires=1702736680&Policy=eyJTdGF0ZW1lbnQiOlt7IkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTcwMjczNjY4MH19LCJSZXNvdXJjZSI6Imh0dHBzOi8vY2RuLWxmcy5odWdnaW5nZmFjZS5jby9FbGV1dGhlckFJL2dwdC1uZW8tMi43Qi9iZDA2ZWVkOTljNzkxMzQ4ZGY1YmVjMDE0YmQzOTk5NjBlZjM2NGI5OTUxZTFiZTgxODA5NDBhMzY2OWE5MDY3P3Jlc3BvbnNlLWNvbnRlbnQtZGlzcG9zaXRpb249KiZyZXNwb25zZS1jb250ZW50LXR5cGU9KiJ9XX0_&Signature=ILBqt5E8Uyjz8HPS3Drd3cLSxeHoa~dcKNseLy0woOIYyR-ufdC6i0n59I~Ba7eE~8Whba-n4FftBAJ49390yn2bMdF7xe-DBTQW2vjf~fZSb1X-a9RpodL5R12QR5Ch6YQAiHTQqUWJKN~N3YeNP0MOAQ3S72ThyWPx-M4NcfpOL4Kz5DZnf0XaP25vXSZThOH28JTFMMw-6rHZ1EEn2Rqn4oNMX~ca6PG3YgcpGgMXpxu~pSLA4JvcsX986cYnbITuPqTE7PYTR1GrSDO~6osvD1SjqpX~zgof7pN751U84gd5hG9RaiVb7zB4QYZUGrHu7aal5u4G1KSj0PprxA__&Key-Pair-Id=KVTP0A1DKRTAX (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)')))"), '(Request ID: f103e268-410c-4046-a0a8-e706b3127485)')
```
When I check the website https://huggingface.co/../cache, I find there is no data. Could you please help to solve this problem? Thanks!!!

**Comment by baoguangsheng** [comment]
The presence of the MaxRetryError suggests an issue with downloading the pre-trained model from https://huggingface.co/EleutherAI/gpt-neo-2.7B. Alternatively, you can attempt a manual download in Python using the following code: `model = AutoModelForCausalLM.from_pretrained('EleutherAI/gpt-neo-2.7B')`.

The incorrect message "https://huggingface.co/../cache" is generated by Hugging Face Transformers when attempting to load the model from local storage. To eliminate this misleading message, I have removed the local storage loading code from the `model.py` file.
