### ISSUE TITLE
Appreciation and One question

### ISSUE THREAD

**Issue by Jacobsonradical** [baoguangsheng/fast-detect-gpt#9]
Hi,

First, I just wanna appreciate your hard work on cleaning all other existing zero-shot codes. This provides convenience to everyone. Many thanks!

Second, I am a little bit confused why this model works well even when the reference model and the scoring model are same. From my understanding, if **_x_** is a candidate passage generated from, say _**gpt-neo-2.7B**_, then if we use another model to rewrite each next token given the previous original tokens, the perturbed **_x_** is not going to be "familiar" to _**gpt-neo-2.7B**_, and thus we can leverage the curvature information from the conditional distribution and do the threshold. 

However, when we use the same model to rewrite each next token, I don't see why this idea works. Perhaps I am not understanding your paper well.

**Comment by baoguangsheng** [comment]
We're glad to hear that our code has been of convenience to you and others.

As for your query regarding the use of the same model for both sampling and scoring, you've brought up an interesting point. In this case, the conditional probability curvature closely correlates with the sum of Likelihood and Entropy, as described in the context of Eq. 5. To further clarify, we conducted an Ablation Study, detailed in Appendix E. In this study, we examined the impact of the Entropy term in the equation. The results indicated that the Entropy term significantly reduced the variance of token-level log probability from 2.1893 to 1.6342. This reduction potentially stabilizes the combined feature in different contexts. 

In terms of the perturbation, our approach differs from that used in DetectGPT. Rather than making MINOR rewrites, we sample alternative tokens on ALL positions. Despite this difference, we borrowed the term 'probability curvature' from DetectGPT due to its close formation to our Eq. 3.

I hope this addresses your queries. Thanks.

**Comment by Jacobsonradical** [comment]
Nice. Then, I agree that this design is really delicate and brilliant. Now figure 1 finally makes sense to me hahaha.  Although you guys still name it "curvature", your paper is fundamentally different than DetectGPT. Fantastic. Hope you guys have a good trip to Vienna!

**Comment by baoguangsheng** [comment]
Thanks for your kind and enthusiastic feedback on our design.

We look forward to the trip to Vienna and the communication with the broader community. Thanks!

**Comment by gitgoready** [comment]
chatglm3  errors：

Traceback (most recent call last):
  File "scripts/local_infer.py", line 90, in <module>
    run(args)
  File "scripts/local_infer.py", line 64, in run
    tokenized = scoring_tokenizer(text, return_tensors="pt", padding=True, return_token_type_ids=False).to(args.device)
  File "/home/user/anaconda3/envs/detectgpt3.8/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 2538, in __call__
    encodings = self._call_one(text=text, text_pair=text_pair, **all_kwargs)
  File "/home/user/anaconda3/envs/detectgpt3.8/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 2644, in _call_one
    return self.encode_plus(
  File "/home/user/anaconda3/envs/detectgpt3.8/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 2717, in encode_plus
    return self._encode_plus(
  File "/home/user/anaconda3/envs/detectgpt3.8/lib/python3.8/site-packages/transformers/tokenization_utils.py", line 652, in _encode_plus
    return self.prepare_for_model(
  File "/home/user/anaconda3/envs/detectgpt3.8/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 3196, in prepare_for_model
    encoded_inputs = self.pad(
  File "/home/user/anaconda3/envs/detectgpt3.8/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 3001, in pad
    encoded_inputs = self._pad(
  File "/home/user/.cache/huggingface/modules/transformers_modules/models--zhipu--chatglm3-6b/tokenization_chatglm.py", line 254, in _pad
    assert self.padding_side == "left"
AssertionError
